# Generated by Django 4.0.6 on 2022-07-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_desafio_birthday_desafio_who_is_alter_desafio_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
